# The language in this case has no bearing - we are going to be making use of "conda" for a
# python distribution for the scientific python stack.
language: c

os:
  - linux
  - osx

env:
    global:
        - DESTINATION_CONDA_CHANNEL="rainwoodman"
        - TARGET_ARCH="x64"
        - CONDA_INSTALL_LOCN="${HOME}/miniconda"

        # Defines BINSTAR_TOKEN for your binstar channel
        - secure: "lgvmgG8M6XjqT9jeTYpVcbY+OaxQ7d65HtcfpmJHTy4jbwsS3hktT2F8DJQLEeWXQV/8GLxKNOJuRRmh+x7SWuVjXXje16oBOCYIrkluJQw4zOGZr1HCK+lqaz3iyqMfmZjUpeETSwNrdqq0lZqQ87DR8SuHAKD2EN3KJfzb6qCTJJPvf8lowLVEq55gkoM9oCafLh+o5aBtbx86rVXeKtPdoaqFlQbhHIy1AJBsxiXYJmxunanL6gTf42H6fzi/5xU2Hx8U+IxNTmxNkbpEURq4XcyxnqjIunH8P4YEsjarIpvAgfH8WqAFXLi8OkaobTGUGIZTn+TQfer3mQz8hCNC8GIWs21Ycn4tmozvvvgK5Cpz4HcKAlSwK0DvlBzusctA58knKVGAw0gkOC7gNH/oP9hv3Zw6uzmxUXu8TA8bARBp3EwH6fAbQwEInletfPi6nENaWCIj0WGg+CS4hM8Xlw4iVuVz8dk3tzIC0Krfi9VyTN8fUwCrvP3mHpKHLe2710hN7UkT9fCoG/mQfPiAva8uyutf1mkjMOyFDg6Wkjqt3MHy8iBxjOezRtcip6H9cAOzaiuQE4r/kCg5LcQz7hAR0QHSMwD6FegiRg5l3bXU+8Bzycl3nifJyTzS6K4cWvl99Z7X9U2aImeVe8lktkzJORPWIg0as2oU9bo="

        # The python build restriction MUST be set at the moment, though it
        # can have any value. The setting below avoids known-bad builds on
        # python 2.6 and 3.3 for some packages.
        - PYTHON_BUILD_RESTRICTIONS="2.7*|>3.4"

        - NUMPY_BUILD_RESTRICTION="numpy >=1.11*"
        # The value below needs to be set but will be ignored.
        - CONDA_NPY="1.11"
        - CONDA_VERSION=4.2*

# Matrix is fully specified (for now) by os versions

install:
    # Install and set up miniconda.
    - if [ $TRAVIS_OS_NAME == "linux" ]; then wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh; fi
    - if [ $TRAVIS_OS_NAME == "osx" ]; then wget http://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh; fi
    - bash miniconda.sh -b -p $CONDA_INSTALL_LOCN
    - export PATH=${CONDA_INSTALL_LOCN}/bin:$PATH
    - conda config --set always_yes true

    # pin conda verson to 4.3.22
    - conda config --set auto_update_conda False
    - echo "conda ==4.3.22" >> ${CONDA_INSTALL_LOCN}/conda-meta/pinned

    - conda install --quiet conda

    # set the ordering of additional channels
    - conda config --append channels rainwoodman
    - conda config --append channels conda-forge # for conda-build-all (will be moved to defaults soon)
    - conda config --prepend channels defaults

    # Install a couple of dependencies we need for sure.
    - conda install --quiet --yes anaconda-client=1.6.2 jinja2 cython pycrypto
    - conda install ruamel_yaml
    - conda install xorg-libxt xorg-libxaw xorg-libx11

    # latest conda build
    - conda install conda-build=3

    # Install conda-build-all
    - conda install -c conda-forge conda-build-all

    # To ease debugging, list installed packages
    - conda info -a

script:
    # Only upload if this is NOT a pull request.
    - INSPECT="--inspect-channels rainwoodman"
    - UPLOAD="";
    - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then
        if [ $TRAVIS_REPO_SLUG = "rainwoodman/conda-channel-rainwoodman" ]; then
          echo "Uploading enabled";
          UPLOAD="--upload-channels $DESTINATION_CONDA_CHANNEL";
        fi;
      fi
    # Get ready to build.
    - python extrude_recipes requirements.yml
    # Packages are uploaded as they are built.
    - if [[ -d recipes ]]; then conda build-all recipes --matrix-max-n-minor-versions 3 --matrix-conditions "python $PYTHON_BUILD_RESTRICTIONS" "$NUMPY_BUILD_RESTRICTION"  $INSPECT $UPLOAD; fi
