# Build specific versions by specifying 'version'
# If 'version' not specified, latest release from pypi is built
# To build past versions in addition, specify a 'past_versions' list

- name: bigfile

