{% set name = "bigfile" %}

package:
  name: {{ name|lower }}
  version: "{{version}}"

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  md5: {{ md5 }}

build:
  number : 1

requirements:
  build:
    - python
    - numpy x.x
    - cython
    - mpi4py

  run:
    - python
    - numpy x.x
    - mpi4py

test:
  # Python imports
  imports:
    - bigfile
    - bigfile.tests

about:
  home: http://github.com/rainwoodman/bigfile
  license: BSD-2-Clause
  summary: 'python binding of BigFile, a peta scale IO format'
  license_family: BSD

extra:
  recipe-maintainers:
    - rainwoodman
